fail_fast: false
repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Format files with cargo fmt.
        entry: cargo fmt
        language: system
        types: [ rust ]
        files: backend/.+\.rs$
        args: [ "--manifest-path", "backend/Cargo.toml", "--" ]

      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        types: [ rust ]
        files: backend/.+\.rs$
        pass_filenames: false
        args: [ "--manifest-path", "backend/Cargo.toml" ]

      - id: clippy
        name: clippy
        description: Lint rust sources
        entry: cargo clippy
        language: system
        args: [ "--manifest-path", "backend/Cargo.toml", "--", "-D", "warnings" ]
        types: [ rust ]
        files: backend/.+\.rs$
        pass_filenames: false

      - id: talisman-precommit
        name: talisman
        entry: >-
          bash -c 'if [ -n "${TALISMAN_HOME:-}" ];
          then TALISMAN_INTERACTIVE=false ${TALISMAN_HOME}/talisman_hook_script pre-commit;
          else echo "TALISMAN does not exist.
          Consider installing from https://github.com/thoughtworks/talisman .
          If you already have talisman installed, please ensure TALISMAN_HOME
          variable is set to where talisman_hook_script resides, for example,
          TALISMAN_HOME=${HOME}/.talisman/bin";
          fi'
        language: system
        pass_filenames: false
        types: [text]
        verbose: true
