version: '3.8'

services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test_pass"
    volumes:
      - ./db-init/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
