version: '3.8'

services:

  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: "pace3"
      POSTGRES_USER: "pace3_user"
      POSTGRES_PASSWORD: "pace3_pass"
    volumes:
      - ./db-init/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
    healthcheck:
      test: "pg_isready -U postgres"
      interval: "10s"
      timeout: "3s"
      start_period: "180s"
      retries: 3
