namespace: pace3-prod
commonLabels:
  variant: prod
bases:
- ../base/

patchesStrategicMerge:
  - ingress.yaml

configMapGenerator:
  - name: pace3-configuration
    behavior: merge
    literals:
     - URL_HOST=www.stadtpark-marathon.de
