
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pace3

resources:
- deployment.yaml
- ingress.yaml
- service-monitor.yaml
- service.yaml
- backup.yaml

configMapGenerator:
- literals:
  - URL_HOST=pace3.lauf-gegen-rechts.de
  name: pace3-configuration
labels:
- includeSelectors: true
  pairs:
    app: pace3
