commonLabels:
  app: pace3

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pace3

resources:
  - deployment.yaml
  - ingress.yaml
  - service-monitor.yaml
  - service.yaml
  - backup.yaml

