describe('Registration', function () {

    it('Registration', function () {


        cy.visit("https://pace3.lauf-gegen-rechts.de/")
        cy.get('[style="position:absolute;right:5%;border:1px solid white"] > .brownbg')
            .click()
        
        cy.get(':nth-child(3) > .input-group > .form-control')
            .type('Vorname')
            .should('have.value', 'Vorname')
        cy.get(':nth-child(4) > .input-group > .form-control')
            .type('Nachname')
            .should('have.value', 'Nachname')
        cy.get(':nth-child(5) > .input-group > .form-control')
            .type('Team Name')
            .should('have.value', 'Team Name')
        cy.get(':nth-child(6) > .input-group > .form-control')
            .type('teamname@teamname.com')
            .should('have.value', 'teamname@teamname.com')
        cy.get(':nth-child(7) > .input-group > .form-control')
            .type('teamname@teamname.com')
            .should('have.value', 'teamname@teamname.com')

        cy.get('#starting_point')
            .select(1).invoke("val")
            .should('eq', 'hamburg')
        cy.get('#starting_point')
            .select(0).invoke("val")
            .should('eq', 'Bitte auswählen')
        cy.get('#starting_point')
            .select(2).invoke("val")
            .should('eq', 'other')
            cy.get('#running_level')
            .select(0).invoke("val")
            .should('eq', 'Bitte auswählen')
        cy.get('#running_level')
            .select(1).invoke("val")
            .should('eq', 'rarely') 
        cy.get('#running_level')
            .select(2).invoke("val")
            .should('eq', 'sometimes')
        cy.get('#running_level')
            .select(3).invoke("val")
            .should('eq', 'often')
        
        cy.get(':nth-child(10) > .input-group > .form-control')
            .clear()
            .type('4')
            .should('have.value', '4')
        cy.get(':nth-child(10) > .invalid-feedback')
            .should('have.text', 'Die Spende muss mindestens 5€ betragen!')
        cy.get(':nth-child(10) > .input-group > .form-control')
            .clear()
            .type('5')
            .should('have.value', '5')

        
        
    })
})
