name: BuildTestDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run backend linting and testing
        run: cd backend && ./run quality_check
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run frontend linting and testing
        run: echo "here goes your tests steps"
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ test-backend, test-frontend ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login to Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: registry.k3s.colodeck.de
          username: github
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push pace3
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: registry.k3s.colodeck.de/pace3:latest
      - name: Build and push migration
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          file: ./backend/Dockerfile.migration
          push: true
          tags: registry.k3s.colodeck.de/pace3-migration:latest
      - name: Build and push pace3 frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend/pace-ui/
          file: ./frontend/pace-ui/Dockerfile.frontend
          push: true
          tags: registry.k3s.colodeck.de/pace3-frontend:latest
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    needs: build
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: kubectl apply -f infra-setup
      - name: reload
        run: kubectl -n pace3 rollout restart deployment pace3-deployment
      - name: wait
        run: kubectl -n pace3 rollout status deployment pace3-deployment --timeout=2200s
