name: BuildTestDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: actions-rs/cargo@v1
        name: lint
        with:
          command: clippy
      - name: Init db
        run: docker-compose up --force-recreate -d    
      - name: Migrate database
        uses: ducharmemp/diesel-cli-action@0.1.0
        with:
          migration_directories: migrations
        env:
          DATABASE_URL: postgres://pace3_user:pace3_pass@localhost:5432/pace3
      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
      - name: Shutdown db
        run: docker-compose down
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: registry.k3s.colodeck.de
          username: github
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.k3s.colodeck.de/pace3:latest
  deploy:
    runs-on: self-hosted
    needs: build
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: kubectl apply -f infra-setup
      - name: reload
        run: kubectl -n pace3 rollout restart deployment pace3-deployment
      - name: wait
        run: kubectl -n pace3 rollout status deployment pace3-deployment --timeout=90s
