name: BuildTestDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: actions-rs/cargo@v1
        name: lint
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.k3s.colodeck.de/pace3:latest
  deploy:
    runs-on: self-hosted
    needs: docker
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: kubectl apply -f infra-setup
      - name: reload
        run: kubectl -n pace3 rollout restart deployment pace3-deployment
      - name: wait
        run: kubectl -n pace3 rollout status deployment pace3-deployment --timeout=90s
