name: Cypress End-to-End Tests
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          working-directory: cypress
