name: Dependencies
on:
  push:
    branches: [ "main" ]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd $GITHUB_WORKSPACE && mv backend/Cargo.* .
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
